name: "ImportErvissData"
on:

  workflow_dispatch:

jobs:

  import_erviss_data_job:
    if: github.repository_owner == 'european-modelling-hubs'
    runs-on: ubuntu-latest
    outputs:
      changed_files:  ${{ steps.import_erviss.outputs.imported_files }} 


    steps:

    # Checkout the hub tools repo for python scripts
    # -------------------------------------------------      
    - name: checkout hub tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'


    # Checkout the data repository
    # -------------------------------------------      
    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/RespiCompass'
        ref: 'main'
        path: './repo/'

    # Setup Pyton env, version 3.10
    # --------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # Install additional packages 
    # --------------------------------
    - run: pip install pandas==1.2.5


    # Run Python script to import erviss data
    # -----------------------------------------
    - name: Import Erviss data
      id: import_erviss
      run: |
        python ./tools/code/SH_get_erviss_data.py --hub_path ./repo --disease_name "ILI"


    # Commit changes to dt
    # -----------------------------------------
    - name: Commit data repo changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Updating Truth Data repo ..."
          default_author: github_actions
          push: true



  call-persisting-wf:
    needs: import_erviss_data_job
    uses: european-modelling-hubs/RespiCompass/.github/workflows/persist_changes.yml@main
    with:
      changes-list: ${{ needs.import_erviss_data_job.outputs.changed_files }}

    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }} 

        
