name: PersistChanges

on:
  # Manually launched
  workflow_dispatch:

  # Other workflows calls
  workflow_call:
    inputs:
    
      # input list of changes is a blank separated string
      changes-list:
        required: true
        type: string
  
    secrets:
      # pass in the GITHUB_TOKEN    
      envPAT:
        required: true


jobs:

  persist_to_json_job:    
    runs-on: ubuntu-latest
    steps:
      
    - name: Trace the changes
      run: | 
        echo "Changes: ${{ inputs.changes-list }}"


    # Checkout the hub tools repo for python utils
    # -----------------------------------------------      
    - name: checkout python tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.envPAT }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'


    # Checkout the data repo
    # -----------------------------------------------      
    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.envPAT }}
        repository: 'european-modelling-hubs/RespiCompass'
        ref: 'main'
        path: './repo/'
    
    # Store changes 
    # -------------------------
    - name: Store Changes 
      env:
        data: ${{ inputs.changes-list }}
      run: |
        python ./tools/code/SH_persist_changes.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Update data storage"
          default_author: github_actions
          push: origin main --force --set-upstream
          # push: true
      env:
        GITHUB_TOKEN: ${{ secrets.envPAT }}
