
name: "UpdateIliPlus"
on:

  workflow_dispatch:

jobs:

  import_iliplus_data_job:
    if: github.repository_owner == 'european-modelling-hubs'
    runs-on: ubuntu-latest
    outputs:
      changed_files:  ${{ steps.import_erviss.outputs.imported_files }} 


    steps:

    # Checkout the hub tools repo for python scripts
    # -------------------------------------------------      
    - name: checkout hub tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'


    # Checkout the data repository
    # -------------------------------------------      
    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/RespiCompass'
        ref: 'main'
        path: './repo/'

    # Setup Pyton env, version 3.10
    # --------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install additional packages 
    # --------------------------------
    - run: pip install pandas


    # Run Python script to import erviss data
    # -----------------------------------------
    - name: Import Ili plus
      id: import_iliplus
      run: |
        echo ">>> Updating ili plus..."
        python ./tools/code/SH_get_ili_plus.py
        echo ">>> Updates completed"
    

    # Commit changes to dt
    # -----------------------------------------
    - name: Commit data repo changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Updating Truth Data repo ..."
          default_author: github_actions
          push: true



  # call-persisting-wf:
  #   needs: import_iliplus_data_job    
  #   uses: european-modelling-hubs/RespiCompass/.github/workflows/persist_changes.yml@main
  #   with:
  #     changes-list: ${{ needs.import_iliplus_data_job.outputs.changed_files }}

  #   secrets:
  #     envPAT: ${{ secrets.GITHUB_TOKEN }} 
